### ISSUE TITLE
Trying your tutorial in 2024

### ISSUE THREAD

**Issue by kingram6865** [shaunwa/react-auth-starter#10]
I'm using NVM to set my node to v9.11.2 which seems to be the version to use with the app dependencies.
I'm not up to speed with the current react-router implementation so I'm attempting to stay close to what the lesson presents.

```
$ nvm current
v9.11.2
```
I get the following error with `npm start. Any suggestions`?

```
> front-end@0.1.0 start /home/kingram/TUTORIALS/LIL/react-auth-starter/front-end
> react-scripts start

/home/kingram/TUTORIALS/LIL/react-auth-starter/front-end/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:29
                } catch {}
                        ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! front-end@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the front-end@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kingram6865** [comment]
I fixed this problem by running create-react-app and copying over the base files.
