### ISSUE TITLE
can you help on this i get this error after 01_08

### ISSUE THREAD

**Issue by Inokcode** [shaunwa/react-auth-starter#2]
i have connect to mongo db url to my mongodb ,after that when i am testing on postman it gives this error

[nodemon] starting `babel-node -r dotenv/config ./src/server.js`
Server is listening on port 8080
(node:18324) UnhandledPromiseRejectionWarning: Error: data and salt arguments required
    at Object.hash (D:\code\REACT-AUTH\react-auth-starter\back-end\node_modules\bcrypt\bcrypt.js:137:17)
    at D:\code\REACT-AUTH\react-auth-starter\back-end\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\code\REACT-AUTH\react-auth-starter\back-end\node_modules\bcrypt\promises.js:20:12)
    at Object.hash (D:\code\REACT-AUTH\react-auth-starter\back-end\node_modules\bcrypt\bcrypt.js:133:25)
    at _callee$ (D:\code\REACT-AUTH\react-auth-starter\back-end\src\routes\/signUpRoute.js:67:39)
    at tryCatch (D:\code\REACT-AUTH\react-auth-starter\back-end\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\code\REACT-AUTH\react-auth-starter\back-end\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\code\REACT-AUTH\react-auth-starter\back-end\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\code\REACT-AUTH\react-auth-starter\back-end\src\routes\signUpRoute.js:16:103)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or 
by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` 
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NirvanaPhX** [comment]
I think it has to do with the bcrypt function you called. Can you paste your code here.
